definitions:
  dto.AcademicYearsPayload:
    properties:
      academic_years:
        items:
          type: string
        type: array
    type: object
  dto.AcademicYearsRequest:
    properties:
      external_ref:
        type: string
      service_name:
        type: string
      userUchprocCode:
        type: integer
    type: object
  dto.Attendance:
    properties:
      topic_number:
        type: integer
      value:
        type: string
    type: object
  dto.AttendanceJournalError:
    properties:
      message:
        type: string
      student_id:
        type: integer
    type: object
  dto.Course:
    properties:
      attendance_id:
        type: integer
      course_name:
        type: string
      credits_count:
        type: string
      group_id:
        type: integer
      is_assistant:
        type: boolean
      point_id:
        type: integer
      start_date:
        type: string
      teacher_name:
        type: string
    type: object
  dto.DeleteTokenRequest:
    properties:
      external_ref:
        type: string
      service_name:
        type: string
      token:
        type: string
    type: object
  dto.FacultiesRequest:
    properties:
      academic_year:
        type: string
      external_ref:
        type: string
      service_name:
        type: string
    type: object
  dto.Faculty:
    properties:
      code:
        type: string
      id:
        type: integer
      name:
        type: string
      specialties:
        items:
          $ref: '#/definitions/dto.Speciality'
        type: array
    type: object
  dto.GetAttendanceJournalPayload:
    properties:
      journal:
        items:
          $ref: '#/definitions/dto.StudentAttendance'
        type: array
    type: object
  dto.GetJournalRequest:
    properties:
      course_id:
        type: integer
      external_ref:
        type: string
      limit:
        type: integer
      service_name:
        type: string
      userUchprocCode:
        type: integer
    type: object
  dto.GetTopicsPayload:
    properties:
      topics:
        items:
          $ref: '#/definitions/models.Topic'
        type: array
    type: object
  dto.Group:
    properties:
      code:
        type: string
      id:
        type: integer
    type: object
  dto.GroupCoursesPayload:
    properties:
      courses:
        items:
          $ref: '#/definitions/dto.Course'
        type: array
    type: object
  dto.GroupCoursesRequest:
    properties:
      academic_year:
        type: string
      external_ref:
        type: string
      group_id:
        type: integer
      service_name:
        type: string
      userUchprocCode:
        type: integer
    type: object
  dto.LoginPass:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  dto.MainFilterPayload:
    properties:
      faculties:
        items:
          $ref: '#/definitions/dto.Faculty'
        type: array
    type: object
  dto.PointJournal:
    properties:
      current_week:
        type: integer
      header:
        items:
          $ref: '#/definitions/dto.Week'
        type: array
      max_point:
        type: integer
      students:
        items:
          $ref: '#/definitions/dto.StudentPoint'
        type: array
    type: object
  dto.PointUpdate:
    properties:
      id:
        type: integer
      point:
        type: number
    type: object
  dto.Response:
    properties:
      code:
        type: integer
      message:
        type: string
      payload:
        type: object
      status:
        type: string
    type: object
  dto.Speciality:
    properties:
      code:
        type: string
      id:
        type: integer
      name:
        type: string
      years:
        items:
          $ref: '#/definitions/dto.Year'
        type: array
    type: object
  dto.StudentAttendance:
    properties:
      attendance:
        items:
          $ref: '#/definitions/dto.Attendance'
        type: array
      id:
        type: integer
      name:
        type: string
      record_book:
        type: string
    type: object
  dto.StudentPoint:
    properties:
      first_rating:
        items:
          $ref: '#/definitions/dto.WeekPoint'
        type: array
      first_rating_sum:
        type: number
      grade:
        type: string
      id:
        type: integer
      name:
        type: string
      points_sum:
        type: number
      record_book:
        type: string
      second_rating:
        items:
          $ref: '#/definitions/dto.WeekPoint'
        type: array
      second_rating_sum:
        type: number
    type: object
  dto.TokenizePayload:
    properties:
      expire_at:
        type: string
      full_name:
        type: string
      token:
        type: string
      user_code:
        type: integer
    type: object
  dto.TokenizeRequest:
    properties:
      external_ref:
        type: string
      login_pass:
        $ref: '#/definitions/dto.LoginPass'
      service_name:
        type: string
    type: object
  dto.TopicAllRequest:
    properties:
      course_id:
        type: integer
      external_ref:
        type: string
      service_name:
        type: string
      userUchprocCode:
        type: integer
    type: object
  dto.TopicDeleteRequest:
    properties:
      external_ref:
        type: string
      service_name:
        type: string
      topicId:
        type: integer
      userUchprocCode:
        type: integer
    type: object
  dto.TopicUpdateRequest:
    properties:
      external_ref:
        type: string
      service_name:
        type: string
      topic:
        $ref: '#/definitions/models.Topic'
      topic_id:
        type: integer
      userUchprocCode:
        type: integer
    type: object
  dto.UpdateAttendanceJournalRequest:
    properties:
      attendance:
        items:
          $ref: '#/definitions/dto.StudentAttendance'
        type: array
      course_id:
        type: integer
      external_ref:
        type: string
      service_name:
        type: string
      userUchprocCode:
        type: integer
    type: object
  dto.UpdatePointJournalRequest:
    properties:
      course_id:
        type: integer
      external_ref:
        type: string
      points:
        items:
          $ref: '#/definitions/dto.PointUpdate'
        type: array
      service_name:
        type: string
      userUchprocCode:
        type: integer
    type: object
  dto.Week:
    properties:
      editable:
        type: boolean
      number:
        type: integer
    type: object
  dto.WeekPoint:
    properties:
      point:
        type: number
      week_number:
        type: integer
    type: object
  dto.Year:
    properties:
      code:
        type: string
      groups:
        items:
          $ref: '#/definitions/dto.Group'
        type: array
      id:
        type: integer
    type: object
  models.Topic:
    properties:
      cnzap:
        type: string
      dtzap:
        type: string
      editable:
        type: boolean
      id:
        type: integer
      kol_kmd:
        type: integer
      kol_lab:
        type: integer
      kol_lek:
        type: integer
      kol_obsh:
        type: integer
      kol_prak:
        type: integer
      kol_sem:
        type: integer
      tema:
        type: string
    type: object
info:
  contact: {}
  title: API
paths:
  /academic_years:
    post:
      consumes:
      - application/json
      parameters:
      - description: token
        in: header
        name: Token
        required: true
        type: string
      - description: Service Name
        in: header
        name: Service
        required: true
        type: string
      - description: Request body
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.AcademicYearsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.AcademicYearsPayload'
      summary: Get academic years
  /attendance_journal/get:
    get:
      consumes:
      - application/json
      parameters:
      - description: token
        in: header
        name: Token
        required: true
        type: string
      - description: Service Name
        in: header
        name: Service
        required: true
        type: string
      - description: Request body
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.GetJournalRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetAttendanceJournalPayload'
      summary: Get attendance journal
  /attendance_journal/update:
    post:
      consumes:
      - application/json
      parameters:
      - description: token
        in: header
        name: Token
        required: true
        type: string
      - description: Service Name
        in: header
        name: Service
        required: true
        type: string
      - description: Request body
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateAttendanceJournalRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.AttendanceJournalError'
      summary: Update attendance journal
  /courses/at:
    post:
      consumes:
      - application/json
      parameters:
      - description: token
        in: header
        name: Token
        required: true
        type: string
      - description: Service Name
        in: header
        name: Service
        required: true
        type: string
      - description: Request body
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.GroupCoursesRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GroupCoursesPayload'
      summary: Get group courses
  /courses/pt:
    post:
      consumes:
      - application/json
      parameters:
      - description: token
        in: header
        name: Token
        required: true
        type: string
      - description: Service Name
        in: header
        name: Service
        required: true
        type: string
      - description: Request body
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.GroupCoursesRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GroupCoursesPayload'
      summary: Get group courses
  /faculties:
    post:
      consumes:
      - application/json
      parameters:
      - description: token
        in: header
        name: Token
        required: true
        type: string
      - description: Service Name
        in: header
        name: Service
        required: true
        type: string
      - description: Request body
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.FacultiesRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.MainFilterPayload'
      summary: Get user faculties, specialities, years and groups
  /ping:
    post:
      description: ping server
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
      summary: ping
  /point_journal/get:
    get:
      consumes:
      - application/json
      parameters:
      - description: token
        in: header
        name: Token
        required: true
        type: string
      - description: Service Name
        in: header
        name: Service
        required: true
        type: string
      - description: Request body
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.GetJournalRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.PointJournal'
      summary: Get poins journal
  /point_journal/update:
    post:
      consumes:
      - application/json
      parameters:
      - description: token
        in: header
        name: Token
        required: true
        type: string
      - description: Service Name
        in: header
        name: Service
        required: true
        type: string
      - description: Request body
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.UpdatePointJournalRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Update poins journal
  /tokenize:
    post:
      consumes:
      - application/json
      parameters:
      - description: token
        in: header
        name: Token
        required: true
        type: string
      - description: Service Name
        in: header
        name: Service
        required: true
        type: string
      - description: Request body
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.TokenizeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.TokenizePayload'
      summary: Tokenize user
  /topic/all:
    get:
      consumes:
      - application/json
      parameters:
      - description: token
        in: header
        name: Token
        required: true
        type: string
      - description: Service Name
        in: header
        name: Service
        required: true
        type: string
      - description: Request body
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.TopicAllRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetTopicsPayload'
      summary: Get all topics
  /topic/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: token
        in: header
        name: Token
        required: true
        type: string
      - description: Service Name
        in: header
        name: Service
        required: true
        type: string
      - description: Request body
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.TopicUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Topic'
      summary: create topic
  /topic/delete:
    post:
      consumes:
      - application/json
      parameters:
      - description: token
        in: header
        name: Token
        required: true
        type: string
      - description: Service Name
        in: header
        name: Service
        required: true
        type: string
      - description: Request body
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.TopicDeleteRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
      summary: delete topic
  /topic/update:
    post:
      consumes:
      - application/json
      parameters:
      - description: token
        in: header
        name: Token
        required: true
        type: string
      - description: Service Name
        in: header
        name: Service
        required: true
        type: string
      - description: Request body
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.TopicUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
      summary: update topic
  /untokenize:
    post:
      consumes:
      - application/json
      parameters:
      - description: token
        in: header
        name: Token
        required: true
        type: string
      - description: Service Name
        in: header
        name: Service
        required: true
        type: string
      - description: Request body
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.DeleteTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Delete user token
schemes:
- http
swagger: "2.0"
